### ISSUE TITLE
[Feature request] teleport and guild chat

### ISSUE THREAD

**Issue by Pantyhose-X** [RisingLeaf/guilds#1]
Add teleport   -- to the guild user location
Add guild chat  -- gui dropdown

**Comment by RisingLeaf** [comment]
I can do the chat, not sure what you mean by teleport

**Comment by Pantyhose-X** [comment]
> I can do the chat, not sure what you mean by teleport

/teleport
/tp
teleport to the location of the online guild user

**Comment by RisingLeaf** [comment]
Both features have been implemented, /gt to teleport to a member of the same guild and the chat is visible in /guilds_menu
sorry that it took so long
